$(document).ready(function(){
    $("#nav__link-group__link__search-id").click(function(){
        $(".search-modal").show(120);
    });
    $(".search-modal__close-btn__btn").click(function(){
        $(".search-modal").hide(100);
    });
    $("#nav__hamburger-container__main-group__ul-group__link-group__link__search-id").click(function(){
        $(".search-modal").show(120);
    });
});