$(document).ready(function(){
    $(".section-modal__main-container__card-group__card-container__button").click(function(){
        $(".section-modal").hide(120);
        $(".pay-modal").show(120);
    });
    $(".pay-modal__top-container__title-close__close").click(function(){
        $(".pay-modal").hide(120);
    });
});